### PR TITLE
Added minor changes to the first example

### PR DESCRIPTION
**Pull request by loganhennes**
@adowling2

### CODE REVIEW

**Comment by adowling2** [comment]
I merged this PR and published it to the website: https://ndcbe.github.io/data-and-computing/notebooks/contrib/Spaghettification.html

Here are a few outstanding issues:
- [ ] In the acknowledgments, link to the website of the professor who inspired this problem.
- [ ] Upload any images you embedded into the notebook into the `/media` folder. This is a great way for each partner to contribute.
- [ ] Your notebook was moved to the `contrib-dev` folder. You need to update your fork to be in sync with main. Do NOT upload a new copy into `contrib` as it will get overwritten.
- [ ] Read through the notebook on the website and fix any typos or formatting issues you see. If you have questions or do not know how to fix something, post here.

**Comment by adowling2** [comment]
Also fix these errors:
```
/Users/adowling/DowlingLab/Teaching/data-and-computing/notebooks/contrib/Spaghettification.ipynb:50002: WARNING: Non-consecutive header level increase; 1 to 3 [myst.header]
/Users/adowling/DowlingLab/Teaching/data-and-computing/notebooks/contrib/Spaghettification.ipynb:60002: WARNING: Non-consecutive header level increase; 1 to 3 [myst.header]
```

This means that you jumped from `#` to `###` in the subsection titles and skipped `##`.

**Comment by loganhennes** [comment]
Is there an easy way to edit the file in github? I want to fix all of the ### BEGIN SOLUTION and ### END SOLUTION so it matches the homework solutions.

**Comment by adowling2** [comment]
@loganhennes You'll want to download the file, edit it in Colab, then reupload the file. Alternately, you can install conda and GitHub desktop on your computer.

**Pull request merged**
