### PR TITLE
Added updated project 1 file - Sarah Nano and Raghav Saxena

### PR DESCRIPTION
**Pull request by raghavsaxena24**
@adowling2

### CODE REVIEW

**Comment by raghavsaxena24** [comment]
I am not sure how to add my partner @snano96 as a contributor?

**Comment by adowling2** [comment]
@snano96 needs to edit the file. I'll post instructions.

**Comment by adowling2** [comment]
I merged this PR and published it to the website: https://ndcbe.github.io/data-and-computing/notebooks/contrib/stochastic-simulation.html

Here are a few outstanding issues:
- [ ] Format the beginning the same as here: https://ndcbe.github.io/data-and-computing/notebooks/contrib/Biotransport-Entrance-Length.html
- [ ] Upload any images you embedded into the notebook into the `/media` folder. This is a great way for each partner to contribute.
- [ ] Your notebook was moved to the `contrib-dev` folder. You need to update your fork to be in sync with main. Do NOT upload a new copy into `contrib` as it will get overwritten.
- [ ] Read through the notebook on the website and fix any typos or formatting issues you see. If you have questions or do not know how to fix something, post here.

**Comment by snano96** [comment]
Hi @adowling2 I am unclear on how I can make changes to the file? I cant seem to find a place where I can open the file and edit it? Or do I need to reupload?

**Comment by snano96** [comment]
@adowling2 I am not able to add any files to the /media folder, it says I require push access to the directory, not sure how to fix this or edit the notebook

**Comment by adowling2** [comment]
Requested changes in #114

**Comment by adowling2** [comment]
@snano96 My guess is that either you need to create your own fork or have write permissions for @raghavsaxena24's fork. We can schedule a time for you to stop by and I can show you how to do this so you appear as a contributor. This is not urgent.

**Comment by snano96** [comment]
@adowling2 I believe I was able to add myself as a contributor

**Pull request merged**
