### PR TITLE
Cleanup Edits for Chap 1

### PR DESCRIPTION
**Pull request by E-Ream**

### CODE REVIEW

**Comment by E-Ream** [comment]
**Note**
The first commit "cleanup update 00-02" should be disregarded as the publish notebooks were edited, the next commit will correctly edit the 00-02 notebooks.

**Comment by E-Ream** [comment]
@adowling2 @jkeane14 
For chapter 1 on the website, notebook 04c-Modules-and-Files is missing and needs to be published.

**Comment by E-Ream** [comment]
@adowling2 @jkeane14 
I'm finding that for some of the markdowns on the github published website the dollar sign formatting for mathematical functions isn't working even though it works when opening the notebooks in jupyter lab.  Below is an example of a markdown first on the website then jupyter lab.

image
image

**Comment by adowling2** [comment]
@E-Ream These links should be helpful when investigating the LaTeX (math equations) limitations:
- https://jupyterbook.org/en/stable/content/math.html
- "Always use double dollar signs for math" (https://github.com/ndcbe/data-and-computing/issues/1#issuecomment-1115334407)

Things I will try:
- [ ] Enable parsing extensions: https://jupyterbook.org/en/stable/content/math.html#latex-style-math
- [ ] Enable HTML extension: https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#html-admonitions

Does this only happen inside the "home activity", "tutorial activity", or "class activity" boxes? Can you post a link here of one notebook that has issues? I'll use it for testing.

**Comment by E-Ream** [comment]
@adowling2 
I've mainly found this issue within the highlighted "activity" boxes but the Gaussian Elimination notebook in chapter 2 is an example of this issue both with a highlighted box as well as in a normal markdown.
[Gaussian Elimination](https://ndcbe.github.io/data-and-computing/notebooks/02-publish/02-Gauss-Elimination.html)

**Comment by E-Ream** [comment]
> @adowling2 @jkeane14 A few quick questions:
> 
> 1. Just to clarify, in terms of hiding the necessary solutions to the begin/end blocks for some of the exercises, since the publish script won't automatically run the notebooks and we run them ourselves, the solutions will be printed as output.  To hide this for when they're published, are we using the hide-output tag or should we clear the output individually for the cells that we want to hide the solution output for?
> 2. The pictures appear in the website notebook but don't appear once you run the notebook in colab.  I'm not sure of how to fix this since the pathway to the media is correct.
> 3. As with the numpy module needing to be added earlier, the matplotlib module also needs to be added.  This may not be an issue now that we are running the notebooks on our own rather than through the publish script?

@adowling2 When you have a chance, could you provide insight to any o these issues?

**Comment by adowling2** [comment]
Let's also fix this warning message:
```
/Users/adowling/DowlingLab/Teaching/data-and-computing/notebooks/01-publish/10-Testing-and-Debugging.ipynb:30002: WARNING: Non-consecutive header level increase; 1 to 3 [myst.header]
/Users/adowling/DowlingLab/Teaching/data-and-computing/notebooks/01-publish/10-Testing-and-Debugging.ipynb:270002: WARNING: Non-consecutive header level increase; 1 to 3 [myst.header]
/Users/adowling/DowlingLab/Teaching/data-and-computing/notebooks/01-publish/10-Testing-and-Debugging.ipynb:270020: WARNING: Non-consecutive header level increase; 1 to 3 [myst.header]
/Users/adowling/DowlingLab/Teaching/data-and-computing/notebooks/01-publish/10-Testing-and-Debugging.ipynb:300002: WARNING: Non-consecutive header level increase; 1 to 3 [myst.header]
/Users/adowling/DowlingLab/Teaching/data-and-computing/notebooks/01-publish/10-Testing-and-Debugging.ipynb:330002: WARNING: Non-consecutive header level increase; 1 to 3 [myst.header]
```

**Comment by E-Ream** [comment]
Warning message about header levels for 01-10 notebook has been fixed.

**Comment by E-Ream** [comment]
@adowling2 
Conflicting files to be resolved before merging

**Pull request merged**
