### PR TITLE
Chapter 4 Draft 3

### PR DESCRIPTION
**Pull request by E-Ream**
See #20 for running list of tasks.

### CODE REVIEW

**Comment by adowling2** [comment]
@E-Ream I merged PR  #53 into this branch. You will not see two scipy notebooks. Please migrate the transformations into your modified scipy notebook and then delete the extra copy with `-Transformations` in the title. Does this make sense?

**Comment by E-Ream** [comment]
@adowling2 Where will I find the transformations?  The notebook with -Transformations in the title doesn't appear for me in the Chap 04 folder, I just see the 04-06-Newton-Methods-in-Scipy.ipynb notebook I had edited.

**Comment by adowling2** [comment]
Did you pull the changes yet? I merge them into this branch.

**Comment by E-Ream** [comment]
That helped fix it, thank you.

**Comment by E-Ream** [comment]
@adowling2 Ready to merge, no conflicts

**Pull request merged**
