### PR TITLE
Updating Notebook Links

### PR DESCRIPTION
**Pull request by E-Ream**

### CODE REVIEW

**Comment by adowling2** [comment]
@E-Ream You can update all of the links in just one PR. Or do one PR per evening (with multiple chapters). When it is ready to merge, tag me. You do not need to do one separate PR per chapter.

**Comment by E-Ream** [comment]
@adowling2 Sounds good, should I still make separate chapter branches or use just one?

**Comment by adowling2** [comment]
One branch is one PR

**Comment by adowling2** [comment]
@E-Ream Here are the warning messages for broken links I get when building the book:

```
/Users/adowling/DowlingLab/Teaching/data-and-computing/notebooks/01/Python-Basics-III-Lists-Dictionaries-Enumeration.ipynb:110002: WARNING: 'myst' reference target not found: ../01-publish/06-NumPy.ipynb
/Users/adowling/DowlingLab/Teaching/data-and-computing/notebooks/06/Newton-Methods-in-Scipy.ipynb:40004: WARNING: 'myst' reference target not found: ../04/Newton-Raphson-Methods-for-Systems-of-Equations.ipynb
/Users/adowling/DowlingLab/Teaching/data-and-computing/notebooks/10/Probability-Basics.ipynb:310010: WARNING: 'myst' reference target not found: rain-ex
/Users/adowling/DowlingLab/Teaching/data-and-computing/notebooks/12/Measuring-Flowrate-Example.ipynb:40002: WARNING: 'myst' reference target not found: ../../media/error-prop-example.pdf
/Users/adowling/DowlingLab/Teaching/data-and-computing/notebooks/15/Monte-Carlo-Uncertainty-Analysis-for-Nonlinear-Regression.ipynb:60002: WARNING: 'myst' reference target not found: ../12/Simulation.ipynb
```

For `error-prop-example.pdf`, check that you are referencing it the same way as an image. If you are, I might need to fix something in the processing script.

**Comment by E-Ream** [comment]
@adowling2 I updated the first three, the last two both work on my local computer when I click the links so I'm not sure why they're not working once the publish script is run?

**Comment by adowling2** [comment]
Thank you for the commit today. These are the two error messages left:
```
/Users/adowling/DowlingLab/Teaching/data-and-computing/notebooks/12/Measuring-Flowrate-Example.ipynb:40002: WARNING: 'myst' reference target not found: ../../media/error-prop-example.pdf
/Users/adowling/DowlingLab/Teaching/data-and-computing/notebooks/15/Monte-Carlo-Uncertainty-Analysis-for-Nonlinear-Regression.ipynb:60002: WARNING: 'myst' reference target not found: ../12/Simulation.ipynb
```

I'll investigate. I do not understand why these are not linking correctly as I see the files.

**Comment by adowling2** [comment]
@E-Ream My investigation is complete:
* We had `Simulation-Motivating-Example.ipynb` in the table of contents. I changed all of the references to `Simulation.ipynb`.
* I had to make a few lines of changes to the notebook processing script to accommodate handouts.

**Pull request merged**
