### PR TITLE
Jessica edits for Chap 1

### PR DESCRIPTION
**Pull request by jkeane14**
**Tasks for** @jkeane14:
- [x] Create a branch, open a PR
- [x] Move this list to the new PR (@adowling2)

Flow Control
- [x] Rename to "Python Basics II: Loopy Logic"
- [x] Remove an content on pseudocode
- [x] Proof read
- [x] Remove autograder tests
- [x] Hide solutions
- [x] Draft learning objectives (few bullet points)

Pseudocode
- [x] Remove content on flow control, keep dart example here
- [x] Proof read
- [x] Remove autograder tests
- [x] Hide solutions
- [x] Draft learning objectives (few bullet points)

Testing and Debugging in Python
- [x] Proof read
- [x] Remove autograder tests
- [ ] Hide solutions

### CODE REVIEW

**Comment by jkeane14** [comment]
@adowling2

**Comment by E-Ream** [comment]
@jkeane14  **Suggestions/Edits for Chap 1:**

03-Python Basics: Loopy Logic
- [ ] Hide answers to first home activity with begin/end solution blocks or just delete answers since they're self-explanatory
- [ ] use begin/end solution block for all of the other home/class activities (example below)
### BEGIN SOLUTION
.... solution code to activity....
### END SOLUTION
- [ ] write up solution inside of begin/end solution block for the final home activity at the bottom

03b-Pseudocode
- [ ] are the todo things something we are doing now or later after we get a first run through all the notebooks?

10-Testing and Debugging in Python
- [ ] in the beginning of the test 1: initial condition block it references (Class 4) so change this to the Chap 01-04 Notebook 
- [ ] test 3 also references Class 1 so maybe reference a notebook instead

07-Matplotlib
- [ ] remove reference to vocareum in learning objectives
- [ ] remove the 3b-i, 3b-ii, etc. references in the titles

**Comment by jkeane14** [comment]
@adowling2 I have been running into this error in a few notebooks when trying to import matplotlib.pyplot, do you know where I might be going wrong?
Screen Shot 2022-05-20 at 5 11 10 PM

**Comment by jkeane14** [comment]
@adowling2 Prof Dowling, I tried to start a new pull request for chapter 4 but did not see the option pop up when I pushed the commit from GitHub desktop. Was I supposed to create a new branch first?

**Comment by adowling2** [comment]
> @adowling2 I have been running into this error in a few notebooks when trying to import matplotlib.pyplot, do you know where I might be going wrong? Screen Shot 2022-05-20 at 5 11 10 PM

You likely need to install `matplotlib` in your conda environment. In the anaconda prompt, run:
``conda install -c conda-forge matplotlib``

We can also walk through this during our next meeting

**Comment by adowling2** [comment]
> @adowling2 Prof Dowling, I tried to start a new pull request for chapter 4 but did not see the option pop up when I pushed the commit from GitHub desktop. Was I supposed to create a new branch first?

Yes, to create a new PR, you need to make a new branch. Did you already commit changes to Chapter 4 to this branch? If so, you can just change the name of this PR.

**Comment by jkeane14** [comment]
> > @adowling2 I have been running into this error in a few notebooks when trying to import matplotlib.pyplot, do you know where I might be going wrong? Screen Shot 2022-05-20 at 5 11 10 PM
> 
> You likely need to install `matplotlib` in your conda environment. In the anaconda prompt, run: `conda install -c conda-forge matplotlib`
> 
> We can also walk through this during our next meeting

This worked, thank you!

**Comment by jkeane14** [comment]
> > @adowling2 Prof Dowling, I tried to start a new pull request for chapter 4 but did not see the option pop up when I pushed the commit from GitHub desktop. Was I supposed to create a new branch first?
> 
> Yes, to create a new PR, you need to make a new branch. Did you already commit changes to Chapter 4 to this branch? If so, you can just change the name of this PR.

I committed changes but when I looked around it seemed to commit to the same branch that Elizabeth made changes on

**Pull request merged**
