### PR TITLE
Emmanuel Barias and Vivian Okorie Final Project 

### PR DESCRIPTION
**Pull request by ebarias**

### CODE REVIEW

**Comment by ebarias** [comment]
This project is ready to be graded

**Comment by adowling2** [comment]
Thank you. The plots would benefit from ~10 minutes of attention to meet publication quality guidelines. The axes labels and numbers are too small. Here are good examples:
https://ndcbe.github.io/data-and-computing/notebooks/16/Reaction-MBDoE.html
https://ndcbe.github.io/data-and-computing/notebooks/01/Publication-Quality-Figures.html

**Comment by adowling2** [comment]
Also, some confusion about vector (bold, lower case) vs matrix (bold, capital) vs scalar (italics, not bold, often lowercase)

Screenshot 2023-12-07 at 1 33 41 PM

**Comment by ebarias** [comment]
Apologies! I completely forgot to edit the plots before turning it in and I fixed the equations to be accurate. I can't seem to figure out how to replace the file within this pull request though. Should I delete this pull request and reupload?

**Pull request closed without merging**
