### PR TITLE
Edits for Chap 3

### PR DESCRIPTION
**Pull request by E-Ream**
01 Taylor Series
- [x] proof read
- [ ] remove autograder
- [ ] hide solutions

02 Finite Difference
- [x] proof read
- [ ] remove autograder
- [ ] hide solutions

03 Example: Heating Metal Slab
- [x] proof read
- [ ] remove autograder
- [x] create solutions
- [ ] hide solutions

### CODE REVIEW

**Comment by E-Ream** [comment]
@adowling2 For this tutorial example we are including as a notebook in this chapter (Example: Heating Metal Slab), do you want me to write up solutions for the class activities or leave them as they are?
image

**Comment by adowling2** [comment]
Yes, solutions would be great. Do you have your notes from class? (Put them between ### BEGIN SOLUTION and ### END SOLUTION).

**Comment by E-Ream** [comment]
> Yes, solutions would be great. Do you have your notes from class? (Put them between ### BEGIN SOLUTION and ### END SOLUTION).

I have all of my class notebook notes but not the tutorial notebooks ones.  I'll work on writing these up if you don't have access to previous notes for it.

**Comment by jkeane14** [comment]
01 Taylor Series
- [ ] proofread

02 Finite Difference
- [ ] proofread

03 Example: Heating Metal Slab
- [ ] proofread
- [ ] look over solutions

**Comment by jkeane14** [comment]
@E-Ream 
notebook 03
- [ ] I was going to try to help with the solutions for the metal slab but didn't know if we had to provide values for things like h or if the solutions are just supposed to be equations. Let me know if I can help with this in some way/what would be most helpful

**Comment by E-Ream** [comment]
@adowling2 @jkeane14 For the 03 Notebook Heating a Metal Slab based off of Tutorial 5, it asks for the student to write up a few expressions (without numbers given yet).  When I am writing the solutions inside of the solution blocks, it gives the warning that the variables aren't defined, which makes sense.  Should we leave it as is or is there a way to have it not give that warning?
image

**Pull request merged**
